default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %> 
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  database: <%= ENV.fetch("DATABASE_NAME", "app_development") %>

development:
  <<: *default
  database: mysauna_db

test:
  <<: *default
  database: mysauna_test
  host: <%= ENV.fetch("TEST_DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("TEST_DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("TEST_DATABASE_PASSWORD", nil) %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "myapp_production") %>
    username: <%= ENV.fetch("DATABASE_USER", "myapp") %>
    password: <%= ENV.fetch("MYAPP_DATABASE_PASSWORD", nil) %>
  cache:
    <<: *primary_production
    database: myapp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: myapp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: myapp_production_cable
    migrations_paths: db/cable_migrate
