default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  database: <%= ENV.fetch("DATABASE_NAME", "app_development") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "mysauna_db") %>
  host: <%= ENV.fetch("DEV_DATABASE_HOST", "db") %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE_NAME", "mysauna_test") %>
  host: <%= ENV.fetch("TEST_DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("TEST_DATABASE_USER", "my_test_user") %> # Docker 内の設定と一致
  password: <%= ENV.fetch("TEST_DATABASE_PASSWORD", "Wctx4PRip21ECfGbW3sgUR9fas7YFl5s") %> # Docker の POSTGRES_PASSWORD に一致

production:
  <<: *default
  database: <%= ENV.fetch("PROD_DATABASE_NAME", "mysauna_db") %>
  username: <%= ENV.fetch("PROD_DATABASE_USER", "mysauna_db_user") %>
  password: <%= ENV.fetch("PROD_DATABASE_PASSWORD", "Wctx4PRip21ECfGbW3sgUR9fas7YFl5s") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>

cable:
  <<: *default
  database: <%= ENV.fetch("CABLE_DATABASE_NAME", "mysauna_cable") %>
  username: <%= ENV.fetch("CABLE_DATABASE_USER", "cable_user") %> 
  password: <%= ENV.fetch("CABLE_DATABASE_PASSWORD", nil) %>

queue:
  <<: *default
  database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "mysauna_queue") %>
  username: <%= ENV.fetch("QUEUE_DATABASE_USER", "queue_user") %>
  password: <%= ENV.fetch("QUEUE_DATABASE_PASSWORD", nil) %>

cache:
  <<: *default
  database: <%= ENV.fetch("CACHE_DATABASE_NAME", "mysauna_cache") %>
  username: <%= ENV.fetch("CACHE_DATABASE_USER", "cache_user") %>
  password: <%= ENV.fetch("CACHE_DATABASE_PASSWORD", nil) %>