default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  database: <%= ENV.fetch("DATABASE_NAME", "app_development") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "mysauna_db") %>

test:
  <<: *default
  database: mysauna_test
  host: <%= ENV.fetch("TEST_DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("TEST_DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("TEST_DATABASE_PASSWORD", nil) %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "mysauna_db") %>
  username: <%= ENV.fetch("DATABASE_USER", "mysauna_db_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
