default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5433) %>
  username: <%= ENV.fetch("DATABASE_USER", "mysauna_db_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  database: <%= ENV.fetch("DATABASE_NAME", "mysauna_db") %>

development:
  <<: *default
  database: mysauna_db
  username: mysauna_db_user
  password: <%= ENV.fetch("DATABASE_PASSWORD", "Wctx4PRip21ECfGbW3sgUR9fas7YFl5s") %>
  host: db

test:
  <<: *default
  database: mysauna_test
  username: mysauna_db_user
  password: <%= ENV.fetch("DATABASE_PASSWORD", "Wctx4PRip21ECfGbW3sgUR9fas7YFl5s") %>
  host: db

production:
  <<: *default
  database: mysauna_db
  username: mysauna_db_user
  password: Wctx4PRip21ECfGbW3sgUR9fas7YFl5s
  host: dpg-ctgf2iilqhvc739jldqg-a.singapore-postgres.render.com
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %> 

cable:
  <<: *default
  database: <%= ENV.fetch("CABLE_DATABASE_NAME", "mysauna_cable") %>
  username: <%= ENV.fetch("CABLE_DATABASE_USER", "cable_user") %> 
  password: <%= ENV.fetch("CABLE_DATABASE_PASSWORD", nil) %>

queue:
  <<: *default
  database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "mysauna_queue") %>
  username: <%= ENV.fetch("QUEUE_DATABASE_USER", "queue_user") %>
  password: <%= ENV.fetch("QUEUE_DATABASE_PASSWORD", nil) %>

cache:
  <<: *default
  database: <%= ENV.fetch("CACHE_DATABASE_NAME", "mysauna_cache") %>
  username: <%= ENV.fetch("CACHE_DATABASE_USER", "cache_user") %>
  password: <%= ENV.fetch("CACHE_DATABASE_PASSWORD", nil) %>